volumes:
  trustanchors:
  custom-ssl:
  cabundle:
  certs:
  usercerts:

services:

  trust:
    build:
      context: ./trust
    volumes:
      - trustanchors:/trust-anchors
      - custom-ssl:/custom-ssl
      - cabundle:/etc/pki
      - certs:/certs
      - usercerts:/usercerts

  nginx:
    image: ${NGINX_IMAGE}:${NGINX_IMAGE_TAG}
    
    ports:
      - "443:443"

    logging:
      driver: "syslog"

    depends_on:
      trust:
        condition: service_completed_successfully

    volumes:
      - custom-ssl:/debian-ssl
      - certs:/certs
      - ./dep.tar.gz:/usr/share/nginx/html/bundles/dep.tar.gz
      - ./nginx/bundle.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts/setup-trust-deb.sh:/docker-entrypoint.d/40-setup-trust.sh

    healthcheck:
      test: ["CMD", "curl", "https://localhost/bundles/dep.tar.gz"]

    networks:
      default:
        aliases:
          - nginx.test.example

  opa-pull:
    image: ${OPA_IMAGE}:${OPA_IMAGE_TAG}
    ports:
      - "8181:8181"

    depends_on:
      nginx:
        condition: service_started
      client:
        condition: service_started
    
    volumes:
      - trustanchors:/trust-anchors
      - cabundle:/etc/pki
      - certs:/certs
      - ./opa/conf:/etc/opa/conf
      #- custom-ssl:/rh-ssl
      #- ./scripts/setup-trust-rh.sh:/docker-entrypoint.d/40-setup-trust.sh

    healthcheck:
      test: ["CMD", "curl", "https://localhost:8181/health"]
    
    command: run --server --log-level debug -c /etc/opa/conf/config-pull.yaml --authentication=token --authorization=basic --tls-ca-cert-file=/trust-anchors/igi_test_ca.pem --tls-cert-file /certs/opa-pull_test_example.cert.pem --tls-private-key-file /certs/opa-pull_test_example.key.pem --addr https://0.0.0.0:8181

    networks:
      default:
        aliases:
          - opa-pull.test.example

  opa-push:
    image: ${OPA_IMAGE}:${OPA_IMAGE_TAG}
    ports:
      - "8182:8182"
    
    volumes:
      - cabundle:/etc/pki
      - certs:/certs
      - ./opa:/etc/opa
      #- ./conf/config-push.yaml:/etc/config.yaml

    depends_on:
      client:
        condition: service_started

    healthcheck:
      test: ["CMD", "curl", "https://localhost:8182/health"]
    
    command: run -s /etc/opa/policies --log-level debug -c /etc/opa/conf/config-push.yaml --authentication=token --authorization=basic --tls-cert-file /certs/opa-push_test_example.cert.pem --tls-private-key-file /certs/opa-push_test_example.key.pem --addr https://0.0.0.0:8182 --watch

    networks:
      default:
        aliases:
          - opa-push.test.example

  client:
    image: ${CLIENT_IMAGE}:${CLIENT_IMAGE_TAG}

    depends_on:
      trust:
        condition: service_completed_successfully

    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki
      #- custom-ssl:/rh-ssl
      - usercerts:/certs
      - ./opa/examples:/opa-examples
      - ./oidc-agent:/home/test/.config/oidc-agent
      #- ./scripts/setup-trust-rh.sh:/docker-entrypoint.d/10-setup-trust.sh
      #- ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh

    healthcheck:
      test: ["CMD", "curl", "https://google.com"]

    entrypoint: sleep infinity