services:

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    
    volumes:
      - ./examples:/opa-examples
      - ./opa:/etc/opa
    
    entrypoint: opa run -s /etc/opa --log-level debug -c /etc/opa/config.yaml --authentication=token --authorization=basic --addr 0.0.0.0:8181 --watch
